### ISSUE TITLE
quiver on relatively large genome 

### ISSUE THREAD

**Issue by PedroBarbosa** [PacificBiosciences/pbcoretools#109]
Hello,

I would like to follow the example described in the latest SMRTtools reference guide regarding the Resequencing Pipeline, particularly the step of splitting the subreads into DataSet chunks by contig.

I have about 65Gb throughput of RSII P6-C4 data, for which I'd like to do consensus calling on a de novo canu assembly (genome size around 900Mb). 

I followed the recommended workflow:

```
bax.h5 -> bax2bam -> reads.bam
reads.bam + reference.fasta -> pbalign -> bamtools -> merged_aligned_reads.bam
```

Now, I'd like to do something similar to  `dataset split --contigs --chunks 8 merged.alignmentset.xml`, but obviously I don't have xml files. Is there any way to parallelize quiver job from my merged bam file? I'm affraid if I do it in the convencional way, I'll have troubles to finish quiver in my local machine (canu assembly took really long time).

Thanks in advance,
Pedro Barbosa

**Comment by mdsmith** [comment]
Hi Pedro, quiver can use multiple cores on a single node using the --numWorkers (-j) option. If you want to chunk the dataset to farm quiver out to multiple nodes you can create an xml file before chunking: `dataset create merged.alignmentset.xml merged_aligned_reads.bam`

**Comment by PedroBarbosa** [comment]
Ok, so the chunking approach is targeted for cluster environment?

I have a fairly powerful machine with 64 CPU(s) and 1Tb RAM, so I've just started quiver with -j option.
Thank you,
Pedro
