### ISSUE TITLE
`bamSieve -n ` doesn't work on dataset input

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbcoretools#81]
Filing from discussion with Nat; I may have mischaracterized.  I need to be able to subsample both subreads and scraps (concordantly), which seems to only work via the dataset mode.  But unfortunately it seems sieving datasets only works with explicit whitelist/blacklist mode, whereas I need -n. 

It seems like this should be perhaps fixable by using the -n directive to precompute a whitelist and then proceed through the same codepath for the whitelist.

**Comment by natechols** [comment]
Try pbcoretools 0.1.12.
