### ISSUE TITLE
pbcoretools module default is incorrect on the cluster

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbcoretools#82]
`module load pbcoretools` is loading 0.1.9, not 0.1.11

you can sort this out with MJ

**Comment by dalexander** [comment]
MJ sez you fix this as follows:

mhsieh [1:50 PM]  
with .version file

[1:51]  
try `find /mnt/software/modulefiles -name '.version'` for the example

**Comment by natechols** [comment]
Yup, that worked.
